apiVersion: v1
kind: Pod
metadata:
  name: nginx-custom
  labels:
    app: nginx-custom
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    resources:
      limits:
        cpu: 3.5
        memory: 2G
